# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\openai\window\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question = QtWidgets.QTextEdit(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(110, 70, 501, 81))
        self.question.setObjectName("question")
        self.answer = QtWidgets.QTextEdit(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(110, 180, 501, 391))
        self.answer.setReadOnly(True)
        self.answer.setObjectName("answer")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 330, 61, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(650, 130, 111, 61))
        self.submit.setObjectName("submit")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(680, 530, 81, 41))
        self.exit.setObjectName("exit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.models = QtWidgets.QComboBox(self.centralwidget)
        self.models.setGeometry(QtCore.QRect(630, 100, 151, 22))
        self.models.setObjectName("models")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(190, 10, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.key.setFont(font)
        self.key.setObjectName("key")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "输入："))
        self.label_2.setText(_translate("MainWindow", "回答："))
        self.submit.setText(_translate("MainWindow", "发送"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.label_3.setText(_translate("MainWindow", "当前使用的模型为："))
        self.label_5.setText(_translate("MainWindow", "输入OpenAI API key："))
